### PR TITLE
Add all Brazil locations

### PR DESCRIPTION
**Pull request by wiliamsouza**
Adds all Brazil localtions.

**DO NOT MERGE UNTIL**

- [x] Add Curitiba
- [x] Add Natal
- [x] Add Brasilia
- [x] Add  São carlos
- [x] Add Recife
- [x] Add Rio de Janeiro

### CODE REVIEW

**Comment by econchick** [comment]
Got it. If this PR could have one commit per location, that'd be great!

**Comment by ellisonleao** [comment]
Hey @econchick @wiliamsouza i think we're done and ready for merge.

**Comment by wiliamsouza** [comment]
@ellisonleao Perfect! Thanks :D

**Comment by econchick** [comment]
Hey @wiliamsouza @ellisonleao - this looks great!  Would you mind putting these locations in alphabetical order before I merge?

**Comment by ellisonleao** [comment]
Done @econchick !

**Pull request merged**
