### PR TITLE
Added new events for August, added resources, changed "chapter" to "group"

### PR DESCRIPTION
**Pull request by ossanna16**
Hey everyone!

I just added the new events for August to the website, added links of previous PyLadies Remote classes to the "Resources" section and changed "PyLadies chapter" to "PyLadies group" on the landing page.

Please merge and deploy when you have time. Thank you! :)
Anna

### CODE REVIEW

**Comment by econchick** [comment]
Should be deployed - thank you @ossanna16 !

**Comment by econchick** [comment]
@ossanna16 separately - do you mind if I make a one-liner script for deployment and save it to your folder? It'd be pretty much the same as the one in the main `pyladies/www` folder.

**Comment by ossanna16** [comment]
Thank you @econchick ! :)

**Comment by ossanna16** [comment]
Would that mean it would be deployed automatically then after it's merched? I don't mind at all. Please do what's easiest for you :)

**Comment by econchick** [comment]
@ossanna16  No, not yet, but it would be easier for me :)

**Comment by ossanna16** [comment]
@econchick I don't mind at all. Thank you, Lynn! :) And also thank you for merging and deploying so quickly.

**Pull request merged**
