### PR TITLE
Made some visual changes. Made the website more appealing :+1:

### PR DESCRIPTION
**Pull request by yasoob**
I hope you guys like it. I really love your initiative. I wanted to contribute so I thought to improve your website a bit. :+1:

### CODE REVIEW

**Comment by yasoob** [comment]
5 days and no update? :) If there is anything which I should improve in my PR then kindly let me know.

**Comment by econchick** [comment]
Hey @yasoob - thank you for the ping!  I *sincere* apologies for not responding sooner.  I'll start reviewing this now!

**Comment by econchick** [comment]
This looks great - thank you so much for the tweaking!  If in the future, you feel so generous with your time, I'd welcome your design input.

Will deploy this shortly!

**Comment by yasoob** [comment]
Well I am available! :) What would you like my help with? I would be glad to chime in.

**Comment by econchick** [comment]
@yasoob  Well a lot of us are web/backend folks, not necessarily frontend/design (e.g. css/html, accessibility), so it's pretty wide open.  We are in the process of creating a new design for the site, I'd check out [pyladies/pyladies-theme](https://github.com/pyladies/pyladies-theme) and ping @viviangb if she needs help/assistance.

**Comment by yasoob** [comment]
I am myself a back-end guy as well :smile: . But I will see what I can do!
:+1:

**Pull request merged**
