### PR TITLE
Modify site template to fix issue #169 for meetup display

### PR DESCRIPTION
**Pull request by willingc**
Fixes the meetup display on home page.

Add an additional check to see if the meetup_id exists for a site. If so, add the meetup to the list of meetup_ids.

### CODE REVIEW

**Comment by willingc** [comment]
@audreyr @econchick If either of you can review this fix and merge, it should correct meetup display on the homepage. Not sure if there should be a trailing `;` at the end of the changed statement. It works without, but js is not my thing ;) If it should have one, I'm happy to edit to update the PR.

**Comment by audreyr** [comment]
Thank you @willingc!

I'd say yes on adding a trailing `;`. Generally they're good to put in with standard JS projects. There are a few weird exceptions of projects that don't use the trailing semicolons, but they're the odd ones out.

Another thing I suggest is breaking the line into separate lines, to make it clearer which `if` goes with which `endif`. To do this without adding extra whitespace, you can add a minus sign to the blocks, as shown in http://jinja.pocoo.org/docs/dev/templates/#whitespace-control. 

Let us know if you need help :)

**Comment by willingc** [comment]
Thanks @audreyr :)
So I broke up the line using the whitespace-control (adding minus signs to the blocks). It runs locally. It looks a little ugly to me, like there should be an easier or cleaner way. If there is, please let me know. Thanks.

**Comment by audreyr** [comment]
Awesome, thanks so much @willingc.

It looks as good as it can, don't worry. With Jinja-templated JS, you can only get so clean, and what you've done is great.

**Comment by audreyr** [comment]
I just verified that it works locally, and that the JS renders without breaking lines. @econchick, this is good to go, just pull and deploy :)

**Comment by willingc** [comment]
@audreyr Thanks for the tips and the review. I learned some JS today. I also learned it's not as pretty as Python :)

**Comment by econchick** [comment]
Deployed - thank you @willingc and @audreyr !

**Pull request merged**
