### PR TITLE
 Adding Pyladies Rural location and logo

### PR DESCRIPTION
**Pull request by PyladiesRural**
We added our location and logo.

### CODE REVIEW

**Comment by Mariatta** [comment]
Hi, thanks for the PR. I checked our system, but I could not find rural@pyladies.com. Have you [submitted the request](https://docs.google.com/forms/d/e/1FAIpQLSeOL0xgRD6jwV3RJxFNApdT_qQN1-3uNomRK4XTfUKSaeDhNg/viewform) to have that account created? Perhaps there was follow up question from that request?

**Comment by lorenanicole** [comment]
@PyladiesRural can you follow up on @Mariatta question?

**Comment by PyladiesRural** [comment]
Hello, girls! We apologyze for taking so long to answer your question, but yes, we have submitted the request to have that account created and we're are using that e-mail right now!

**Comment by Mariatta** [comment]
I checked again, and yes I was able to find rural@pyladies.com. Thanks!

**Pull request merged**
