### PR TITLE
Update 2013-04-19-django-resources.md

### PR DESCRIPTION
**Pull request by williln**
Updated Two Scoops to 1.8 (yay!!), added Django Girls tutorial.

### CODE REVIEW

**Comment by williln** [comment]
So I know I'm supposed to also change the filename to today's date... but I edited this file directly in the browser and don't see a way to do that. Should I delete this PR, change the file name on my machine, and use git to create a new PR with the new filename?

**Comment by econchick** [comment]
Hmm, maybe yea :-/

**Comment by williln** [comment]
Should I move the file into the 2015 directory, or leave it in 2013 and just change the date in the filename?

**Comment by econchick** [comment]
probably moved to 2015 too

**Pull request closed without merging**
