### PR TITLE
Changes added for the mx chapter

### PR DESCRIPTION
**Pull request by MidoriR**
Try to edit for adding the web page and the changes in locations, also added the logo to assest/img and I was wondering about the meetup id, I really don't know where to get that info.

### CODE REVIEW

**Comment by estherbester** [comment]
Hi @MidoriR!  Looks like your base domain is currently set to "https://yourdomain.com" (I see numerous places where this appears) - should that be changed?

**Comment by MidoriR** [comment]
Hi @estherbester, I already changed that to mx.pyladies.com, but I actually wasn't sure if that was going to be our base domain. Let me know if it worked :)

**Comment by econchick** [comment]
Hi @MidoriR! I think for this to work, I think you'll have to do a lot of relative linking for your local resources. So instead of `"https://mx.pyladies.com/css/styles.css"` it should be `css/styles.css`. 

Also, FYI we do _not_ support `https` on the `pyladies.com` domain, unfortunately. So if you need the `mx.pyladies.com` site to be over `https` (e.g. you have forms that people can fill out), then let me know, and we can talk about it.

**Comment by MidoriR** [comment]
Hi @econchick I tried to do the relative linking, let me know if it worked. Also, I don't think the https is necessary for now so it's ok if it the site remains as mx.pyladies.com

**Comment by willingc** [comment]
I'm going to go ahead and close this PR as stale. @MidoriR and others, please let me know if you wish to update or submit a new PR.

**Pull request closed without merging**
