### PR TITLE
Update meetup ids

### PR DESCRIPTION
**Pull request by andressavldrs**
Item 1 from  #150

### CODE REVIEW

**Comment by lorenanicole** [comment]
I finally got MeetUp credentials to use the API! I can write a script to automate this ... or we can even add a GitHub action to update this Ha! Let me run this list against my script to verify.

**Comment by lorenanicole** [comment]
So I actually ran my script against the MeetUp api and found some meetup ids that are inconsistent including those that don't have a meetup chapter that don't have a meetup with the name specified in our `config.yml` .... thoughts on what is the best way to move this forward @willingc? 

Should we:

- Accept this PR
- I make a new PR with this file?

Or:

- Merge it all into one PR

[pyladies_meetup_chapters.txt](https://github.com/pyladies/pyladies/files/3860188/pyladies_meetup_chapters.txt)

**Comment by willingc** [comment]
Either is fine @lorenanicole. Do whatever is easiest for you. Feel free to merge as I've approved.

**Comment by lorenanicole** [comment]
I've just re-ran the script on the _existing_ meetup chapters ... I'm going to update this with the actual chapters in the PyLadies Chapter Directory on Sunday! Thanks @willingc I'm going to push up a new `config.yml` in this PR.

**Pull request closed without merging**
