### PR TITLE
Added May event and updated resources section

### PR DESCRIPTION
**Pull request by ossanna16**
Please merge and deploy. Thank you! :)

### CODE REVIEW

**Comment by estherbester** [comment]
Hi @ossanna16, so sorry for the delay! I believe the remote site is now going to be served someplace else? Should I still merge this, though? I can, if it needs to be

**Comment by ossanna16** [comment]
Referring this to @ceaess :)

**Comment by ceaess** [comment]
Yep! Communication failure on my part- I added you to the org, but I'll also send an email. Closing this and I'll send you some docs

**Comment by Astra4587** [comment]
Документация

**Pull request closed without merging**
