### PR TITLE
Pyladies Owerri url

### PR DESCRIPTION
**Pull request by pyladiesowerri**
Please we need a url for PyLadies Owerri
Let it be something like 
Www.imo.pyladies.com

@lorenanicole

### CODE REVIEW

**Comment by Mariatta** [comment]
We can setup the custom url to imo.pyladies.com. Where should this point to?

**Comment by pyladiesowerri** [comment]
I will upload my PyLadies Owerri website code to it.

**Comment by willingc** [comment]
Thanks @pyladiesowerri

**Comment by treasurechristain** [comment]
thanks @willingc

**Pull request merged**
