### PR TITLE
Restructure home page of remote.pyladies.com

### PR DESCRIPTION
**Pull request by treyhunner**
selection_455

Changes:

- Use lighter navigation bar
- Set background color and text color for header area
- Add copy to homepage (copy written by @ossanna16)
- Move Twitter and Eventbrite widgets
- Use transparent SVG logo
- Upgrade Bootstrap and move custom CSS into separate CSS file
- Minor code style improvements

I'm happy to make further changes.  I can also squash any commits if/when desired.

### CODE REVIEW

**Comment by ossanna16** [comment]
@willingc @audreyr @estherbester Could one of you please merge @treyhunner's pull request and deploy? Thanks a lot! :)

**Comment by econchick** [comment]
FYI this won't deploy with the Circle CI setup - I'll still need to be the one that deploys this one.  If someone else can review/merge (I'm on the road for the next two weeks for vacation) I can deploy.

**Comment by econchick** [comment]
Thanks @estherbester! Will deploy when I get to a place with wifi.

**Comment by ossanna16** [comment]
Thank you @estherbester and @econchick :)

**Comment by econchick** [comment]
deployed!! sorry for the wait!!

cc @ossanna16 @estherbester @treyhunner

**Comment by ossanna16** [comment]
Thank you so much @econchick !

**Pull request merged**
