### PR TITLE
Corrections for Salvador's chapter

### PR DESCRIPTION
**Pull request by geisasantos**
line indented and logo in the _assets/images directory

### CODE REVIEW

**Comment by econchick** [comment]
is this any different than #278?

**Comment by geisasantos** [comment]
@econchick just some corrections.

**Comment by econchick** [comment]
@geisasantos yeah but I think the fixes also got into #278. Can you double check with current master, if this is still needed?

**Comment by geisasantos** [comment]
Sure :)

**Comment by geisasantos** [comment]
@econchick is it ok now?

**Comment by geisasantos** [comment]
Hey, @econchick !
Our blog is on and already set up using Github Pages.
Can you setup DNS to point to pyladiessalvador.github.io ?

**Comment by geisasantos** [comment]
Hi, @econchick :)
Can you help us on this?

**Comment by econchick** [comment]
@geisasantos If you could squash your three commits into one so we can keep a clean history, I'll merge this ([a how-to on squashing](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)) cc @estherbester

**Comment by willingc** [comment]
@geisasantos and others, I've opened an issue #369 to track updating the location information. I'm going to close this PR as stale, and we can work through any updates on the new issue.

**Pull request closed without merging**
