### PR TITLE
Update config

### PR DESCRIPTION
**Pull request by pyladiesowerri**
edited my social media account

# PyLadies Pull Request
_Please document the following. We will aim to be as timely as possible in processing your pull request, however as this is a volunteer staffed project anticipate at least a week for pull requests to start to be reviewed._ 

## Is this pull requesting adding or updating a [PyLadies chapter information](https://github.com/pyladies/pyladies#to-add-a-new-pyladies-location)? 

- [x] Yes
- [ ] No

### If you marked yes, is this chapter registered in the PyLadies Chapter Directory?

- [x] Yes
- [ ] No

### If you marked no, please register your chapter using the following form [here](https://forms.gle/LYT6TzjgJ437Y4mr8). The form can only be accessed by being logged into your official PyLadies email account. Were you able to complete the registration?

- [ ] Yes
- [x] No, I could not because [add response below]:

## Have you confirmed the website builds locally with your chapters? See [here](https://github.com/pyladies/pyladies#run-the-site-locally).

- [x] Yes
- [ ] No

## Does your pull request pass the `ci/circleci: build` check? See [this example pull request, in the `All checks have passed` section](https://github.com/pyladies/pyladies/pull/461).

- [x] Yes
- [ ] No

# Pull Request Checklist

- [x] Fill out all sections above
- [ ] Share pull request in PyLadies Slack channel #project-tech-infra

/cc @pyladies/tech-and-infra-admins

### CODE REVIEW

**Comment by pyladiesowerri** [comment]
Hi, please merge pyladies to the chapter list... i uploaded out webiste now

@Mariatta @lorenanicole

**Comment by Mariatta** [comment]
Sorry but I'm not sure what the actual change here. You mentioned in the PR that this is to "edited my social media account", but the change in the yml file is quite massive. What change are you trying to make?

**Comment by pyladiesowerri** [comment]
I previously inputted a wrong social media handle. So I now changed it to
the correct handle

**Comment by Mariatta** [comment]
Then, can you please update the PR to contain only the social media change, instead of 1000 lines of code change?

**Comment by lorenanicole** [comment]
Bumping - please update only the individual line that makes the change for the social media handle rather than a 1000 line code!

**Comment by lorenanicole** [comment]
We will be closing this PR is not resolved by June 20 2020 Hack. Thank you!

**Pull request closed without merging**
