### PR TITLE
Adding Tokyo to loactions.

### PR DESCRIPTION
**Pull request by myoshimu**
Updated config.yaml to include Tokyo information

### CODE REVIEW

**Comment by econchick** [comment]
Hey @myoshimu!

Just a few things:

1. There's no need to commit a new image specifically for Tokyo if you're going to use the standard square one; it's already in the `www/_assets/images` folder as [`pyladies-sq-logo.png`](https://github.com/pyladies/pyladies/blob/master/www/_assets/images/pyladies-sq-logo.png).  So in the `image:` line, you can just put `pyladies-sq-logo.png`
2. Is `http://pyladies.tokyo` the website?  It doesn't work for me.  Also, chapters are required to use the `pyladies.com` subdomain system, e.g. `tokyo.pyladies.com`.  However, if you need a new domain setup (e.g. a `.tokyo` domain), we can talk.  The Python Software Foundation holds the PyLadies trademark, as well as manages our domains for us (e.g. pays for the expenses).
3. Can you squash all your commits into one commit.  A good how-to can be found [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).

Please let me know if you have any questions or if there's any confusion.  And please `@` ping me when you're ready.

Thanks!

**Comment by myoshimu** [comment]
Hi Lynn,

Thanks for looking into my pull request.

>There's no need to commit a new image specifically for Tokyo if you're
going to use the standard square one;

We will replace the Tokyo logo using that file name. Should I replace the
file name to " pyladies-sq-logo.png" until the Tokyo specific logo is ready?

>Is http://pyladies.tokyo the website?

Yes, the website looks like something like weird park domain, but currently
we are constructing the website and the domain above will be used soon.

>Can you squash all your commits into one commit. A good how-to can be
found here.

Got it. I will try squashing the commits.

Thanks!
Miki

2015-08-11 2:07 GMT+09:00 Lynn Root <notifications@github.com>:

**Comment by econchick** [comment]
Hi @myoshimu - yes go ahead and replace the filename to "pyladies-sq-logo.png" then make a new Pull Request when the Tokyo logo is ready.

Thanks!

**Comment by myoshimu** [comment]
Once closing

**Comment by myoshimu** [comment]
Hi Lynn,

Talking with Tokyo girls, we decided changing the domain to "
tokyo.pyladies.com".
Would you put the dummy files for the Tokyo domain?

Thanks,
Miki

2015-08-14 2:15 GMT+09:00 Lynn Root <notifications@github.com>:

**Pull request closed without merging**
