### PR TITLE
Changed django-resources

### PR DESCRIPTION
**Pull request by williln**
Changed Two Scoops edition to 1.8 
Added Django Girls blog tutorial 
Renamed file to reflect today's date 
Moved file to 2015 dir 
Deleted old file from 2013 dir 

I think I'm serious this time.

### CODE REVIEW

**Comment by econchick** [comment]
1 small thing! could you squash your three commits into one?  If you are unfamiliar with rebase/squashing, [this](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) is a good resource.

**Comment by williln** [comment]
I think I did this, but the commits aren't changing here: 

image

When the rebase completed, I did a git push since I didn't actually see the commits get "squashed" on the website, but that also doesn't seem to have done anything. But when I do git rebase -i HEAD~N with N all the way up to 8, I only see the one squashed commit. 

image

Did I do this right?

**Comment by econchick** [comment]
You need to actually change the commits you want to squash from "pick" to "squash"

**Comment by williln** [comment]
I think I didn't explain the second screenshot-- I did change the two commits I wanted to squash from "pick" to "squash," and that rebase went through fine. When I didn't see the commits in the browser change, however, I tried to rebase again, and that's the screenshot above-- to me, it looks like there is only one commit related to the changes I made; all the other comments are other commits. 

So I'm not sure why the commits in the browser aren't "squashing" as now there is nothing left to "squash" according to Git :-/ 

Thinking I should delete my fork, re-fork, re-make the changes, do one commit, and open a new PR. :-./

**Comment by econchick** [comment]
no no don't!  here's the process I would do (hold on!)

**Comment by econchick** [comment]
```bash
$ git rebase -i HEAD~3
# switch the last two from "pick" to "squash"
# then ESC + wq
$ git push --force origin master  # or wherever you previously pushed
```

The `--force` is to force update in which would update your PR

**Comment by williln** [comment]
Lalalala! I think I did it!

**Comment by econchick** [comment]
will deploy in a few minutes.

Thanks so much for your help!!

**Comment by williln** [comment]
Thank you so much for YOURS! :)

**Comment by willingc** [comment]
@econchick Kermit! Love this :)

@williln Lynn's rebase is exactly what I use too.

**Pull request merged**
