### PR TITLE
PyLadies Remote website

### PR DESCRIPTION
**Pull request by ossanna16**
Hey Lynn!

I think the PyLadies Remote website is good to go. Let me know if you need me to do adjustments and changes.

As a URL I would like http://remote.pyladies.com if possible.

If possible, could the website go live early next week? Katie is doing a "Python in your PJs" class on the 28th and I think it would be a good first event to promote for the PyLadies Remote chapter :)

Thank you!
Anna

### CODE REVIEW

**Comment by econchick** [comment]
Hey Anna! I'll get this reviewed when I'm at work tomorrow. Thanks!

**Comment by ossanna16** [comment]
Thank you! :)

**Comment by econchick** [comment]
Hey @ossanna16 !

A couple of things:

* Your git config isn't setup with your email address, which is desired.  You can see when you do `git config` within the PyLadies repo where that is necessary:

```bash
$ pwd
~/Dev/pyladies/remote
$ git log
# <--- snip --->
commit a1f50f9e10060e68e74648570cfc4e1158d53dad
Author: Anna <Anna@Annas-MacBook-Air.local>
Date:   Mon Jun 8 17:33:23 2015 +0200

    added remote

commit 00bf86f1a1d23c0addc79442abac87b442ff6dda
Merge: d60e12f 4d504a7
Author: Lynn Root <lynn@spotify.com>
Date:   Fri May 29 11:07:25 2015 -0400

    Merge branch 'pr/180'

commit 4d504a7c862b8e31a0dc92a633010e706a81040d
Author: mei-li <meili.tr@gmail.com>
Date:   Tue May 26 22:36:23 2015 +0200

    fix organisers design issue
```

You can add your email address by running the following command in any directory (this will setup git's config _globally_ so other repos you contribute to will see this as well):

```bash
$ git config --global user.email "your_email@example.com"
```

* I'd like to keep commit history within the PyLadies repo clean.  This lends to more of preference to "[atomic commits](https://en.wikipedia.org/wiki/Atomic_commit)", but more trying to keep a logical & [tidy history](http://stackoverflow.com/questions/6543913/git-commit-best-practices).  So therefore, I'd like you to squash all of your four commits into one.  I find [this tutorial](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) very helpful, and I suggest doing this _after_ you set your git config email above.  Once you squashed it locally, you will have to force push to your master branch (this pull request will automatically update).  This means adding the `-f` flag when you `git push`.  

* I find the EventBrite register widget a little confusing.  For one, I don't think a calendar view is needed, but that's my personal preference.  But mainly the "Register!" text above the calendar is confusing - I expected it to be a link to something: 

2015-06-12 at 9 47 am

Maybe if you were to change that text to be more like "Upcoming Events:".  

* I find the landing page a little stark - mostly because of the "white space":
2015-06-12 at 9 49 am

May I suggest something a long the lines of a background image behind the the "PyLadies Remote" image and text, something along the lines of [this Bootstrap example](http://getbootstrap.com/examples/carousel/).


If you'd like to address the first three, I can get that merged in & deployed pretty quickly if you don't think you can do #4 with a quick turn around.  I'd also like to ping @willingc and @audreyr to take a look too :)

**Comment by willingc** [comment]
@ossanna16 Bravo to the developer :) Lynn's suggestions are all reasonable (and kudos to her for the helpful tips).

I'll be around tomorrow (son's graduation today) if you need any help with the `git config` or rebasing and squashing commits.

A couple of tips that I found helpful for the rebase/squash dance:
- `git remote -v` is useful to seeing if you have remotes set up properly
- I tend to avoid `git pull` in favor of `git fetch` followed by `git rebase` when I am updating upstream changes into my local repo. I find it saves me time by avoiding many merge conflicts
- Create a checklist for yourself on "how to squash" that you understand. It will help you in the future (well, at least it helped me)

I'm going to defer the front end stuff to @econchick and @audreyr. They are much more experienced here than me. 

Go Anna go! :balloon: :cake::penguin:

**Comment by ossanna16** [comment]
Hey @econchick!

Thank you for your feedback and the really helpful instructions!

Thank you also @willingc for your kind words :)

So I ran the git config --global command so it should have worked.

Also squashing all of the commits from remote into one commit worked I think. While doing the rebasing I must have done something wrong. I just saw that I added 6 commits to this pull request which aren't mine and are already merged. I'm super sorry about that :( How can I remove those commits from this pull request?

I changed the "Register!" to "Upcoming Events" like you suggested. I don't really like the other Eventbrite widgets. I liked the calendar one the best. But if you really dislike it, I could change it.

I agree with you that the website looks a little stark. I like the idea of a background image but I really struggle with bootstrap so if you or @audreyr or someone else could help with that, that would be awesome and much appreciated:)

I'm sorry that I keep messing things up. I'm still learning how to use git properly.

Thanks for all your help!

**Comment by willingc** [comment]
Anna, Let's see if I can explain what happened with the rebase. I think you did the rebase correctly; yet, it captured the other individual's commits likely because you are developing on your master branch and there have been new commits by others since you started your development. You will save yourself much time and headaches if you develop on a newly created branch each time you add a feature (use `git branch <branchname>` to create new branch. `git checkout <branchname>` is what you use to change to work on a different branch. `git branch -v` will list all branches. `git status` will tell you the current branch you are on.

So how to fix:
`git status`, `git log`, `git fetch`, `git rebase`, `git push`, and `git reset` will be used. It's helpful if you understand that each commit has a SHA1 hash.

More to follow...

**Comment by willingc** [comment]
@ossanna16 Okay, I looked at the history on your repo and I think these steps should help.

From your local machine in the base of your pyladies repo:

1.` git status`  (you should be on your master branch)
2. `git log -n7`  (will show you the last 7 commits in your log)
3. `git remote -v`  (this should show all your remotes - you should have origin which should direct to your ossanna/pyladies repo and you should have upstream which should direct to the pyladies/pyladies repo. If you do not have these, you will have to add or change the remotes to this.)
4. `git fetch upstream`
5. `git rebase upstream/master`
6. `git log -n7` (you should see the log history have your rebased commit and then the most recent commit from pyladies/pyladies master branch)
7. `git push origin master` (if it complains that it can't: you need to do a force push (use with caution on anything other than your own repo `git push -f origin master`)

Ping me with any questions.
Next time, you will save yourself lots of time and headache if you create a feature branch to work on instead of master. `git branch new-feature` then `git checkout new-feature`. `git status` should show you are on the new-feature branch.

Good luck!

**Comment by ossanna16** [comment]
Thank you for the tips and instructions, @willingc! :)

Ian saved me again and helped me with it so except for the design looking a little stark, everything should be fine now :)

**Comment by willingc** [comment]
@ossanna16 Yay for Ian :)

@audreyr Can you merge? I actually don't have privileges on this repo. Thanks!

**Comment by audreyr** [comment]
@willingc sure, it's merged now. I checked the settings of this repo, and it looks like you have a pending invitation. Search your email.

@ossanna16 nice work!

**Comment by willingc** [comment]
@audreyr Hmm... I checked my email and spam and don't see an email. Likely I deleted it in a mass delete since I only use this particular email for GitHub. If you wouldn't mind telling GitHub to resend, thanks.

Thanks for merging the PR. Nicely done @ossanna16.

**Comment by audreyr** [comment]
@willingc No problem at all, I just canceled and resent it :outbox_tray:

**Comment by ossanna16** [comment]
@audreyr and @willingc:

Does one of you know how we can get the website for PyLadies Remote deployed?
I don’t know if I need to do anything else or if one of the administrators will do it.

**Comment by estherbester** [comment]
@ossanna16 I have not deployed anything yet but I do have the ability, and some free time this evening, so I will take a look!

**Comment by ossanna16** [comment]
Thank you, @estherbester ! :)

**Comment by econchick** [comment]
@ossanna16 @estherbester I went ahead and deployed it; I just realized that while @estherbester can deploy, it's not at all documented how :-/ especially outside of the `www` directory.  I should do that :D

**Comment by willingc** [comment]
@audreyr The new email to accept organization or push privileges hasn't come through. Though I have had a bucket load of other GitHub emails. Any thoughts? GitHub gremlins. :mouse:
cc/ @estherbester, @econchick

**Comment by econchick** [comment]
@willingc - just cancelled and resent - let me know if that worked!

**Comment by willingc** [comment]
@econchick Yes it worked this time! Definitely GitHub gremlins @audreyr :mouse2: :mouse2: :mouse2:
:question: :question: :question: Thanks everyone :)

**Comment by ossanna16** [comment]
Thank you @econchick! :)

**Pull request merged**
