### PR TITLE
Updated event info and added new organisers for Pune

### PR DESCRIPTION
**Pull request by Shrreya**
We have added three new organisers to the Pune team and would love to have their names on the site.
Also, could we add them to the google group for organisers?

### CODE REVIEW

**Comment by econchick** [comment]
@Shrreya with the google group, have them request to join [here](https://groups.google.com/forum/#!forum/pyladies-group-organizers) per the kit instructions.

I'll take a look at this PR later today.

**Comment by Shrreya** [comment]
Sure. Thanks @econchick.

**Comment by Shrreya** [comment]
Hey @econchick did you get a chance to review this PR?

**Comment by Shrreya** [comment]
Hey @econchick @estherbester Unable to see the changes reflected on the site. When can we expect the same to be deployed?

**Comment by econchick** [comment]
@Shrreya @estherbester looks like CircleCI failed to deploy upon merging; I don't have time to look into why at the moment, but give me a few minutes and I'll manually deploy now.

**Comment by Shrreya** [comment]
Thanks a lot @econchick :)

**Pull request merged**
