### PR TITLE
Update blog contributing guidelines with documentation for special ch…

### PR DESCRIPTION
**Pull request by lorenanicole**
…aracter encoding in markdown

### CODE REVIEW

**Comment by estherbester** [comment]
this looks good to merge

**Comment by willingc** [comment]
@lorenanicole If you want to rebase this, that would be dandy.

**Comment by willingc** [comment]
@lorenanicole Do you want to rebase or close this PR?

**Comment by lorenanicole** [comment]
Let's just close it haha. It's been so long.

**Pull request closed without merging**
