### PR TITLE
Chicago Pyladies Page!

### PR DESCRIPTION
**Pull request by celeen**

### CODE REVIEW

**Comment by econchick** [comment]
Hey thanks @celeen !

A couple of things:

* please squash all 18 commits into one - a decent overview of how-to can be found [here](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/)
* You have three .dot files/folders that should not be in your commit:
    * `.com.apple.timemachine.supported`
    * `.sass-cache/3fb02017831e8728217719d03ddea83672c9894a/style.scssc`
    * `chicago/.sass-cache/3fb02017831e8728217719d03ddea83672c9894a/style.scssc`

Otherwise, the actual site looks great!

**Comment by celeen** [comment]
Thanks, @econchick !

I made the changes mentioned, and added a location box for Chicago. I kept our subdomained site and the location box in separate commits, since they deal with different sections of the webstie- would you prefer I squash those together as well?

**Comment by econchick** [comment]
hey @celeen - thanks! it's perfectly fine to have those in two separate commits.

However, I think this change happened during this pull request and you didn't update your branch: if you check out `www/config.yml`, you see that all the relevant www/locations/index.html information is right there.  Please undo your `www/locations/index.html` changes and add them to `www/config.yml`.

Let me know if that's confusing!

**Comment by celeen** [comment]
Oh, magnificent. It's that easy! Thanks again, @econchick !

**Comment by econchick** [comment]
Ah sorry one last thing!  the `config.yml` is in alphabetical order - would you mind readjusting?  Sorry for being such a pain!

**Comment by celeen** [comment]
@econchick No! No pain at all. I should have noticed! Hopefully that does it. :D

**Comment by econchick** [comment]
deployed! thanks for your patience!

**Pull request merged**
