### PR TITLE
Merge pull request #3 from pyladies/master

### PR DESCRIPTION
**Pull request by williln**
Getting in sync

### CODE REVIEW

**Comment by econchick** [comment]
not sure what's going on here :)  when you try to bring in the most up to date from master, I would have this set up:

```bash
# list current remotes
$ git remote -v
origin	git@github.com:pyladies/pyladies (fetch)
origin	git@github.com:pyladies/pyladies (push)

# set up so that your "origin" points to *your* fork
$ git remote set-url origin git@github.com:williln/pyladies.git

# check what remotes are set to now
$ git remote -v
origin	git@github.com:williln/pyladies.git (fetch)
origin	git@github.com:williln/pyladies.git (push)

# set an "upstream" remote to the "real" pyladies repo
$ git remote add upstream git@github.com:pyladies/pyladies
# check what remotes are set to now
$ git remote -v
origin		git@github.com:williln/pyladies.git (fetch)
origin		git@github.com:williln/pyladies.git (push)
upstream		git@github.com:pyladies/pyladies.git (fetch)
upstream		git@github.com:pyladies/pyladies.git (push)
```

Then when you want to merge/sync up with the pyladies master:

```bash
$ git pull --rebase upstream master
```

The `--rebase` will to "magic" to pull in the commits since you last merged in the master upstream branch, and put any of your commits on top of them (if you have any) making it super clean.

And when you want to make a pull request, push to your origin:

```bash
$ git push origin master
```

And then make the pull request from GitHub directly.

I'm going to go ahead and close this pull request.  Hopefully the above makes sense.

**Comment by williln** [comment]
Ack, I thought I'd backed out of this. I clearly cannot Git. Sorry!

**Comment by williln** [comment]
So when I try to do ```git pull --rebase upstream master```, this happens: 

```
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.```

What do I need to do differently? And thank you for your patience :)

**Comment by econchick** [comment]
Ah I think I typo'ed.  Try:

```bash
$ git remote set-url upstream git@github.com:pyladies/pyladies.git
```

and then try again (I think it's because the `.git` wasn't at the end of the URL originally)

**Comment by williln** [comment]
Ah, I think it was actually my SSH key! I am slowly figuring this out... thank you so much.

**Comment by econchick** [comment]
No problem! git is definitely not noob friendly.

**Pull request closed without merging**
