### PR TITLE
PyLadies São Carlos - Updates - Modal, Correction Portuguese

### PR DESCRIPTION
**Pull request by fcschmidt**
It corrected a few words in Portuguese.
And added a modal example.

### CODE REVIEW

**Comment by econchick** [comment]
Thanks so much @fcschmidt !  

I think the `.idea` directory and related files are related to your own IDE.  Could you:

1. Add the `.idea/` line item to your `.gitignore`
2. Commit the `.gitignore`
3. Rebase all your commits (the 4 here and the one when adding the line to `.gitignore`) into one commit (useful how-to if unfamiliar with squashing [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

Let me know if that's confusing or if you need any help.

Thanks!

**Comment by fcschmidt** [comment]
Hi @econchick. I have added the `.idea` folder on `.gitignore` and squashed all commits in one.

Is it all ok now?

Thaanks so much. :tada: :beers:

**Comment by econchick** [comment]
Did you not want this merged?

**Comment by fcschmidt** [comment]
No, I saw that there are some errors. And we decided to do differently.

**Comment by econchick** [comment]
Ah okay - no problem!

**Comment by fcschmidt** [comment]
Thanks! :beers:

**Pull request closed without merging**
