### PR TITLE
mexico city pyladies location

### PR DESCRIPTION
**Pull request by valerybriz**
Adding the pyladies mexico city location

### CODE REVIEW

**Comment by willingc** [comment]
Hi @valerybriz. To add a pyladies location, the `www/config.yml` file should be edited to add the new location. The information is alphabetical order by city. The entry for Mexico City would be similar to the other locations listed. There is no need to add  `www/locations/cdmx/index.html` since the mynt static site generator will do that for you.

**Comment by valerybriz** [comment]
> Hi @valerybriz. To add a pyladies location, the `www/config.yml` file should be edited to add the new location. The information is alphabetical order by city. The entry for Mexico City would be similar to the other locations listed. There is no need to add `www/locations/cdmx/index.html` since the mynt static site generator will do that for you.

Thank you for your response, I'm almost done on editing it, I just have one question, how can I get our meetup Id?

Thank you!

**Comment by willingc** [comment]
Good question about the meetup id @valerybriz. I'm not sure if there is an easy way. I used the API console offered by meetup at this url (https://secure.meetup.com/meetup_api/console/?path=/:urlname). I sent a request for your meetup group name and the JSON response had the id `19719503`. (PS You may need to create an API token to use this) Screenshot follows:

Screenshot 2019-05-21 08 55 56

**Comment by valerybriz** [comment]
> Good question about the meetup id @valerybriz. I'm not sure if there is an easy way. I used the API console offered by meetup at this url (https://secure.meetup.com/meetup_api/console/?path=/:urlname). I sent a request for your meetup group name and the JSON response had the id `19719503`. (PS You may need to create an API Key to use this) Screenshot follows:
> 
> Screenshot 2019-05-21 08 55 56

Thank you very much, I just double checked and it certainly is 19719503
:D

**Comment by willingc** [comment]
I just rendered this PR locally, and I found two things that you need to update this PR:

- Add the image `pyladies_cdmx.png` into the `www/_assets/images` directory
- Correct `config.yml` name so that it renders proper Unicode. Use `CDMX, M&eacute;xico` for the name

With these two changes, this PR should be ready to merge. 👍

**Comment by valerybriz** [comment]
> I just rendered this PR locally, and I found two things that you need to update this PR:
> 
> * Add the image `pyladies_cdmx.png` into the `www/_assets/images` directory
> * Correct `config.yml` name so that it renders proper Unicode. Use `CDMX, M&eacute;xico` for the name
> 
> With these two changes, this PR should be ready to merge. 👍

Done! thank you very much for your instructions :D :D

**Comment by willingc** [comment]
And it's live... Great job on the PR and changes @valerybriz. 💐 🍰 I love the logo too.

Screenshot 2019-05-21 11 52 53

**Pull request merged**
