### PR TITLE
Add Paris location.

### PR DESCRIPTION
**Pull request by patjouk**
Hi!
I've created a page (www/locations/paris) and added info to config.yml

### CODE REVIEW

**Comment by econchick** [comment]
Hey @patjouk - so this looks really good, but one thing - not sure if you knew - we have our own [Code of Conduct](http://kit.pyladies.com/en/latest/policies.html#code-of-conduct) that locations "abide by".  It's also on our [homepage](http://www.pyladies.com/CodeOfConduct/).  How do you feel about switching out the Geek Feminism Wiki one for ours?

**Comment by patjouk** [comment]
Hi!
I needed to translate it in French, that why I started working on the CoC.
I realized that the definition of harassment in Pyladies CoC is not complete: it needs more details on what is not permitted. I prefer "Offensive comments related to gender, gender identity and expression, sexual orientation, disability, mental illness, neuro(a)typicality, physical appearance, body size, race, or religion" other "offensive verbal/electronic comments related to personal characteristics or choices" for example. I don't want people who are harassed to hesitate to report a breach of CoC because they're not sure if "it's bad enough" (that what happen in Paris first meetup). It also missed part on misgendering someone: it's important for our event because we try to be trans and genderfluid friendly.
This part on the GF CoC ("The Geek Feminism community prioritizes marginalized people’s safety over privileged people’s comfort.") is also very important to me: It's covering the basic trolling we received from the start. I want to have it written somewhere to not repeat it all the time ;)
That why I said we are using Pyladies CoC, reinforced by GF wiki CoC. Is it Ok for you?

**Comment by econchick** [comment]
@patjouk this is an *amazing* criticism of the current CoC, and you bring up such valid points.  I'm actually currently adding content to the kit (including info from Geek Feminism on how to respond to CoC reports), and I think this is a good time to review the CoC itself as well.  I'll start a conversation on the organizers mailing list within the next day or two about it.

**Comment by patjouk** [comment]
Thanks! This is awesome :heart:

**Pull request merged**
