### PR TITLE
1st Global Council Announcement

### PR DESCRIPTION
**Pull request by Marie-L**
# PyLadies Pull Request
_Please document the following. We will aim to be as timely as possible in processing your pull request, however as this is a volunteer staffed project anticipate at least a week for pull requests to start to be reviewed._ 

I've updated the last blog post with Bethany's name and I've also added our first announcement.

### CODE REVIEW

**Review by Mariatta — APPROVED** [review]
Looks good to me. Thanks. Are you able to merge this yourself?

**Comment by Marie-L** [comment]
Thanks @Mariatta ! No, I don't have permission. Can you please merge it when you have time? Thanks 😊

**Comment by BethanyG** [comment]
@Mariatta I was waiting for the tests to pass....I can merge this now.  @Marie-L went to bed.  😄

**Comment by Marie-L** [comment]
Thanks @BethanyG 😊

**Pull request merged**
