### PR TITLE
added Polish chapter to the list of locations

### PR DESCRIPTION
**Pull request by aniawsz**

### CODE REVIEW

**Comment by econchick** [comment]
Hey @aniawsz ! Thanks so much for the PR!  Just a small nitpick: could you put the Poland information in alphabetical order in the `www/config.yml`? The `pyladies.com/locations` page renders the order directly on the yaml file.

Thanks!

**Comment by aniawsz** [comment]
Sure, will do, thanks!

2015-03-10 17:42 GMT+01:00 Lynn Root <notifications@github.com>:

**Comment by aniawsz** [comment]
done!

**Comment by econchick** [comment]
Deployed - thanks!

**Pull request merged**
