### PR TITLE
New Location Blumenau, Brazil

### PR DESCRIPTION
**Pull request by aliniribeiroo**

### CODE REVIEW

**Comment by lorenanicole** [comment]
@aliniribeiroo  when was the `blumenau@pyladies.com` email address created?

**Comment by aliniribeiroo** [comment]
> @aliniribeiroo when was the `blumenau@pyladies.com` email address created?

Not Yet. i send an email following the cookbok asking to create an email for our chapter, but i steel don' t get an answer. I can change to our currently email.

**Comment by Mariatta** [comment]
@aliniribeiroo We have launched the new [PyLadies Prospective Organizer Guide](http://kit.pyladies.com/en/latest/prospective/index.html) Please read through it to understand the process for starting a new PyLadies group.
Once you're ready, please fill in the [PyLadies Chapter Request](https://forms.gle/QFUcNSRGE3XqzPu76) form.

**Comment by lorenanicole** [comment]
@aliniribeiroo did you all have a chance to request a new chapter via the form?

**Pull request closed without merging**
