### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by BrisbanePyLadies**
Adding Brisbane location

### CODE REVIEW

**Comment by Mariatta** [comment]
Tanks! Looking great. I think BPLlogo.jpg should be committed too, right?

**Comment by BrisbanePyLadies** [comment]
In which folder should I commit the logo?

**Comment by willingc** [comment]
Hi @BrisbanePyLadies, The logos go in the following location: `www/_assets/images` https://github.com/pyladies/pyladies/tree/master/www/_assets/images I think you will need to modify #409

**Comment by willingc** [comment]
Resolved merge conflict and this should now add the custom logo (super cute too).

**Comment by treasurechristain** [comment]
Hi, please i want to add pyladies imo, owerri  to the location, how can i go about it?

**Pull request merged**
