### PR TITLE
Update PyLadies DF info

### PR DESCRIPTION
**Pull request by BrunaNayara**
I updated all pyladies DF info

### CODE REVIEW

**Comment by Mariatta** [comment]
Hi, thanks for the PR and sorry for the delay in responding. Looking in our system, I saw both PyLadies Brasilia (brasilia@pyladies.com) and PyLadies Brazil (brazil@pyladies.com) Are these different chapters or the same?

**Comment by willingc** [comment]
@BrunaNayara Please let us know if the chapters are different. I think they are, but confirmation would be helpful. Thanks.

**Comment by BrunaNayara** [comment]
Hi, these are different chapters. Brasilia is the capital of Brazil.

**Comment by willingc** [comment]
@BrunaNayara Thanks for the clarification. If you fix the conflict, I will be happy to review again :smile:

**Comment by BrunaNayara** [comment]
Oh, ok. I haven't seen that. 
But it's done now ;)

**Comment by willingc** [comment]
Changes should be live now @BrunaNayara. Great logo too :smile:

**Pull request merged**
