### PR TITLE
EuroPython 2016 report blog post

### PR DESCRIPTION
**Pull request by lorenanicole**
- 518 words (yeeps a bit longer than recommended in directions)
- Properly formatted and looks beautiful locally

### CODE REVIEW

**Comment by lorenanicole** [comment]
@econchick if you can peep this?

**Comment by econchick** [comment]
Hey @lorenanicole - a couple of small things:

1. Can you squash all your 4 commits into one? Here's a nice [howto](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) if you're not familiar with rebase/squash.
2. I think it's our font, but it may be the parser too - but it doesn't do well with special characters.  This is just an example, but it's littered throughout the whole post (you'd think we'd get unicode right by now...):

**Comment by lorenanicole** [comment]
@econchick when you merge you have the option to squash actually, that's what I had assumed you'd do :-)

**Comment by lorenanicole** [comment]
@econchick fixeeeddd 
image

**Comment by lorenanicole** [comment]
Fixeeeddd @econchick & squashed
image

**Pull request merged**
