### PR TITLE
Update resources

### PR DESCRIPTION
**Pull request by yasoob**
Added free Intermediate Python book to the resources and updated an old url.

### CODE REVIEW

**Comment by yasoob** [comment]
Let me push only 1 commit and not the other one.

**Comment by econchick** [comment]
Could you update your branch to the current master? I merged your previous PR.

**Comment by econchick** [comment]
Hmm not sure why I didn't merge this yet - thanks so much!

**Comment by yasoob** [comment]
No problem :) Thanks for merging.

Kind regards,
Muhammad Yasoob Ullah Khalid <http://yasoob.me/>
Book: book.pythontips.com
Blog: pythontips.com

**Pull request merged**
