### PR TITLE
Adding PyLadies Brazil to locations

### PR DESCRIPTION
**Pull request by aninhalacerda**
Just added all Pyladies Brazil info into Locations page.

### CODE REVIEW

**Comment by aninhalacerda** [comment]
hey @econchick , after I had to add Brazil chapter into locations, I realized the mess that that file was going to become. So I took some time (with *sed* and *egrep* help) to extract all location data to the *config.yml* file and I wrote a generic html in *locations/index.html*. I think now will be easier to add new and maintain current locations.  
  
Hope it helps, let me know if I miss something :)

**Comment by aninhalacerda** [comment]
@econchick any thoughts around this?

**Comment by econchick** [comment]
@aninhalacerda ah super sorry! thanks for the ping.  I will review this PR this afternoon! Promise!

**Comment by econchick** [comment]
Holy crap this is awesome - just what is needed - thank you SO much!  I've merged it locally; will push it when I've finished with the other PRs.

THANK YOU!

**Comment by aninhalacerda** [comment]
great! :) Happy that helped.

thanks

**Pull request merged**
