### PR TITLE
First commit: adding location details.

### PR DESCRIPTION
**Pull request by PyLadiesSA**
# PyLadies Pull Request
_Please document the following. We will aim to be as timely as possible in processing your pull request, however as this is a volunteer staffed project anticipate at least a week for pull requests to start to be reviewed._ 

## Is this pull requesting adding or updating a [PyLadies chapter website](https://github.com/pyladies/pyladies#to-add-a-new-pyladies-location)? 
 

- [ ] Yes
- [x] No

## Have you confirmed the website builds locally? See [here](https://github.com/pyladies/pyladies#run-the-site-locally).

- [x] Yes
- [ ] No

##  Does your pull request pass the `netlify/pyladies/deploy-preview` check?

- [x] Yes
- [ ] No

# Pull Request Checklist

- [x] Fill out all sections above
- [x] Share pull request in PyLadies Slack channel #project-tech-infra

/cc @pyladies/tech-and-infra-admins

### CODE REVIEW

**Comment by lorenanicole** [comment]
@ PyLadiesSA, as part of the ongoing work to centralize the PyLadies chapters we request all chapters please start with these instructions - https://github.com/pyladies/pyladies#to-add-a-new-pyladies-location-to-the-pyladies-website.  Specifically registering your chapter in our directory, registering your organizers so we can add to the GitHub org, and adding your PyLadies website to our repo list.

**Review by lorenanicole — CHANGES_REQUESTED** [review]
@PyLadiesSA, in order to merge this into pyladies.com and as a part of the ongoing work to centralize the PyLadies chapters we request all chapters please start with these instructions - https://github.com/pyladies/pyladies#to-add-a-new-pyladies-location-to-the-pyladies-website. Specifically registering your chapter in our directory, registering your organizers so we can add to the GitHub org, and adding your PyLadies website to our repo list.

**Review by PyLadiesSA — COMMENTED** [review]
Submitted request to register chapter.

**Comment by lorenanicole** [comment]
> Submitted request to register chapter.

Hmm, where? I'm looking at the github.com/pyladies/chapter-websites repo and don't see any open pull requests. Thanks! 
image

**Comment by lorenanicole** [comment]
@PyLadiesSA can you link to your other PR?

**Pull request closed without merging**
