### PR TITLE
Add chapter map to location page

### PR DESCRIPTION
**Pull request by helenst**
I thought I'd have a go at this, using Mapbox :smile:

I felt like it was probably best to leave the existing info in place for now as it's nice to be able to browse all at once, and probably good for SEO. It's also where the map popups get their content from.

I know normally chapters manage their own info but I have bulk geocoded the existing ones and added lat/lng

ref #149

### CODE REVIEW

**Comment by econchick** [comment]
I'm on mobile so I haven't had a chance to look deeply at this - but is the map box API key supposed to be "public"?

Also could you squash this into one commit?

Looking forward to checking it out once I get time (probably tomorrow).

**Comment by willingc** [comment]
@helenst Looks like you are off to a good start. I was looking at the same time as @econchick (waves hello). If you need help on the rebase, please ask.

@econchick I think I may like CircleCI better than Travis.

**Comment by helenst** [comment]
The API key is a public token and meant for embedding in webpages. The one that's in there is linked to my mapbox account but can be swapped very easily for any other. https://www.mapbox.com/help/define-access-token/

I have rebased. Look forward to seeing what you think :-)

**Comment by econchick** [comment]
Hey @helenst - just looking at this now.  Thanks so much for making a crack at it!  Just a couple of things:

1. What do you think of going with the "Light" version (found [here](https://www.mapbox.com/maps/))?
2. Not sure how feasible this is, but instead of the default markers for locations, what about using the [PyLadies Geek](https://github.com/pyladies/pyladies/blob/master/www/_assets/images/pyladies-geek-light-blue.png) (there are other colors too)?
3. There's a lot of space in the North and South: 2015-07-27 at 3 02 pm  are you able to trim the top and bottom a bit?
4. The map also seems to be overlapping the top two location "card squares": 
2015-07-27 at 3 04 pm
5. I **really** _really_ love the little cards that pop up when you click on a marker.  Very nicely done.  Could you make the CSS match the style of the current "card squares"?  Specifically the location name links and the icon links: 
2015-07-27 at 3 06 pm

Seriously. This is super awesome and I can't wait to get this out there.

**Comment by helenst** [comment]
Thanks so much for your awesome feedback! Hopefully I'll have some time a little later in the week to have another look at it! :smile:

**Comment by helenst** [comment]
OK - some updates

1. Switched to 'light' theme
2. Pylady icon is an awesome idea :-) I have added this - the shape lends itself nicely to a map marker, however, it's quite white at the bottom which doesn't stand out well against the light map theme. Tried giving it some drop shadow but doesn't seem to help that much. Wonder if dark theme might be better - what do you reckon?
screenshot-localhost 8080 2015-08-01 18-22-04 vs 
screenshot-localhost 8080 2015-08-01 18-22-40

3. Played around with the height a bit and I *think* it's better but tbh I wasn't seeing those huge amounts of space that you are.

4. Fixed overlap

5. Tweaked styles to match cards. :)

**Comment by econchick** [comment]
AHHH this looks sooo good!!!111!!

I personally don't have a preference for dark/light.  I am perfectly fine with what you'd like to choose.  Let me know (and update PR if necessary), then I'll go ahead and deploy this!!

**Comment by helenst** [comment]
OK, I'm going with dark!

**Comment by econchick** [comment]
Awesome!  will be deployed in a few minutes.  Thank you so much!!

**Comment by helenst** [comment]
:balloon: Thank you for the great code reviews!

**Pull request merged**
