### PR TITLE
Work in progress PR for links 

### PR DESCRIPTION
**Pull request by williln**
So I've added the links, changed the CSS, and added some inline styles to make the text center appropriately. 

I know I'll need to rebase these commits at some point (git was not my friend today) but since I want to make the inline styles into regular styles (because we shouldn't be doing inline styles, right?), I wanted y'all to take a look. 

Thanks for your help and sorry for the slow going on this! CC @econchick @willingc @audreyr

### CODE REVIEW

**Comment by willingc** [comment]
My note to Anna may help you too :) https://github.com/pyladies/pyladies/pull/184

**Comment by williln** [comment]
@willingc squashed into 1 commit! Sorry this took so long-- I was waiting to hear if inline styles were okay. Since I haven't heard anything, I assume they are? 

I do see this message, FWIW. I'm not sure what it means. Let me know if it's something I need to worry about! 

screen shot 2015-07-12 at 3 34 06 pm

**Comment by econchick** [comment]
Don't worry about the "some checks have failed" - it's nothing to do with your PR.

Thanks so much for doing this!  A couple of things:

1. Can we shrink the space between the buttons?  Maybe to about 1/3 the amount of space there currently is?
2015-07-12 at 2 36 pm
2. It looks like the actual links are reversed: the "Get Swag" links to the stickers site, and vice versa :)

Otherwise, this looks great to me!

**Comment by williln** [comment]
Thanks @econchick. How embarrassing!  

So something interesting is happening in my local environment. When I make changes and restart the server, the changes revert back to what they were before. It's so odd-- I can watch it happen on my screen. It happens when I restart the server and this button pops up (I always click "allow"): 

screen shot 2015-07-12 at 6 31 24 pm

What it means is that I can't mess with the CSS because I can't actually preview any changes, since my changes always revert right before my very eyes. I have no idea what could be happening, but I shall Google.

**Comment by williln** [comment]
Update: I have tried to Google, and I've looked at the Mynt docs, but I can't figure out what's causing this behavior. I may have to find someone to pair with on it, which probably won't happen for a couple weeks because of Django Girls Portland. I made a movie of what's happening so you can see. It's so bizarre. https://www.dropbox.com/s/dcvevjaslmmzfug/pyladieswtf.mov?dl=0

**Comment by williln** [comment]
Okay! I am back in business. @econchick what do you think of this spacing? 

screen shot 2015-07-14 at 8 05 45 pm

**Comment by sigmavirus24** [comment]
:clap: Looks awesome!

**Comment by econchick** [comment]
I agree with @sigmavirus24 ! Will merge & deploy now :D

**Comment by williln** [comment]
YAAAAAAAAY! Thanks everyone for all your help. Sorry this took so long! But I learned a ton. :-)

**Pull request merged**
