### PR TITLE
Adding PyLadies Duque de Caxias

### PR DESCRIPTION
**Pull request by pgrangeiro**

### CODE REVIEW

**Comment by econchick** [comment]
Hey @pgrangeiro - could you maintain alphabetical order with the config.yml file?

**Comment by pgrangeiro** [comment]
Done :heart:

**Comment by econchick** [comment]
Hey @pgrangeiro - I'm sorry to be a pain, do you mind rebasing your 2 commits into one? [Here's a good tutorial on how](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) if you're not familiar.

**Comment by pgrangeiro** [comment]
Done :heart: 
And thx again @econchick !

**Comment by econchick** [comment]
Thank you so much! I manually/locally merged this, and it should be deployed!

**Comment by pgrangeiro** [comment]
thx :heart: :heart: :heart:

**Pull request closed without merging**
