### PR TITLE
Update 2015-05-03-django-resources.md

### PR DESCRIPTION
**Pull request by williln**
Changed Djangogirls tutorial URL as it was pointing to the polls tutorial 

(After all that, I had a copy-paste error... Sorry)

### CODE REVIEW

**Comment by willingc** [comment]
@williln no problem :) Nice rebase before. Just a small thing (which quite possibly is an editor thing), there is a trailing " in line 38 that is not needed. Unfortunately the trailing quote leads to a URL which 404s since it can't find the page due to the ".

You should be able to remove the " and then follow the same process as the last PR to squash the commits :)

**Comment by williln** [comment]
I think I did it @willingc! Thanks :)

**Comment by willingc** [comment]
@williln I think you did it too. Thank you!

@econchick LGTM. Ready to merge :)

**Comment by econchick** [comment]
Thanks @williln and @willingc !

**Pull request merged**
