### PR TITLE
PyLadies Pune website

### PR DESCRIPTION
**Pull request by Shrreya**
Hey there!

We have created a simple website for PyLadies Pune. Please check it out and suggest any changes if required.

We would like the URL to be http://pune.pyladies.com.

Can the site go live on August 1st?

Regards,
Shrreya

### CODE REVIEW

**Comment by econchick** [comment]
Hey @Shrreya ! looks good to me.  I'll merge this now and put a calendar reminder to have it deployed on August 1st.  I'll probably do it July 31st in the evening since it'll be the 1st in your timezone by then, if that's okay.

Cheers!

**Comment by Shrreya** [comment]
Sure. Thanks @econchick ! :)
If convenient, you can even deploy it before August 1st.

**Comment by econchick** [comment]
Oh great! I'll do it right now then - it'll probably up within 24 hours though.  Setting up DNS both on the host side and are nameserver side can add a bit of lag.

I just noticed, though - there isn't information on pyladies.com/locations about Pune.  Would you mind making a quick PR? you'd just have to add the info on the `www/config.yml` file (make sure to maintain alphabetical order).

**Comment by Shrreya** [comment]
Alright. I'll do it right now.

**Pull request merged**
